default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres

development:
  <<: *default
  database: VtexAPI_development

test:
  <<: *default
  database: VtexAPI_test

production:
  <<: *default
  database: VtexAPI_production
  username: VtexAPI
  password: <%= ENV['VTEXAPI_DATABASE_PASSWORD'] %>
